name: Publish Quarto site

on:
#  schedule:
#    - cron: "*/15 * * * *" # every 15 minutes
#  workflow_dispatch: # allow manual trigger
  push:
    paths:
      - "swell_data.csv"
    branches: 
      - main
      - gh-pages

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R dependencies
        run: Rscript -e 'install.packages(c("dplyr", "lubridate", "tidyr", "gt"))'

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECT_KEY: ${{ secrets.PROJECT_KEY }}
          API_KEY: ${{ secrets.API_KEY }}
