name: Publish Quarto site

on:
  schedule:
    - cron: "*/15 * * * *" # every 15 minutes
  workflow_dispatch: # allow manual trigger
  push:
      branches: 
      - main
      - gh-pages

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R dependencies
        run: Rscript -e 'install.packages(c("tidyverse", "lubridate", "ggplot2", "gt"))'

      - name: Render site
        run: quarto render

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
          publish_branch: gh-pages
